getsentry/raven-node

lib/parsers.js
test/raven.parsers.js

Swap out for deprecated hostname

---

lib/client.js
lib/transports.js

References #108 
``ca`` parameter will be given to HTTPS requests. If http, it will don't change anything.
I tested it on my setup but I wasn't able to write tests. If you have an idea of to implement shuch tests, tell me and I'll write them.

Use custom certificate for HTTPS

---

README.md
lib/client.js
test/raven.client.js

Included in Protocol v6 as defined in [the protocol docs](http://sentry.readthedocs.org/en/7.0.0/developer/client/index.html). This implementation pulls its information from the constructor's `options` or `process.env.RELEASE` or `process.env.VERSION` (in that order).
This makes the client fully compatible with Sentry 7+
I've included some basic tests as well as an addition to the README which provides a quick introduction regarding the use of the feature.
**TODO**
- Bump `package.json` version
- Release into the wild

Added support for RELEASE tag

---

README.md
lib/transports.js

**Passing extra HTTP transport options**
```javascript
var raven = require('raven');
var client = new raven.Client('{{ SENTRY_DSN }}', {transportOptions: {rejectUnauthorized: false}});
```
fix #115

Add passing extra options to HTTP transport

---

lib/client.js
package.json
test/raven.client.js

Fixes #134, refs #83
Adds 3 new public methods, whose signatures matches the equivalent methods raven-js:
* `setUserContext`
* `setExtraContext`
* `setTagsContext`
Additionally, `extra` and `tags` can be specified during client initialization (again, like raven-js):
```javascript
var client = new raven.Client('DSN', {
extra: { foo: 'bar' },
tags: { browser: 'Chrome 46.0' }
});
```
Note that `user` cannot be specified via `raven.Client` – for no particular reason, other than that's what raven-js does and I'm trying to be as consistent as possible with that library.

Implement global context + add context API methods

---

package.json

This is for issue #152 to handle a null exception if no node modules are loaded (required).

Update lsmod to 1.0.0

---

lib/parsers.js
test/raven.parsers.js

Coerce error.name to string before assigning as type (fixes #155)

---

package.json

This PR updates the `license` property in `pacakge.json` with the currect SPDX license expression syntax for the BSD license for this project `BSD-2-Clause`:
```
npm info package.json raven@0.11.0 license should be a valid SPDX license expression
```

Use correct SPDX license expression syntax for BSD license

---

.gitignore
package.json

Adding [istanbul](https://gotwarlost.github.io/istanbul/) for code coverage. After that a good idea can be add a badge about the test code coverage percentage in the repository (using services such as [https://coveralls.io/](https://coveralls.io/) ).
Opinions? Suggestions? Concerns ?

Add code coverage in test suit

---

.eslintignore

As it stands if you try to `npm test` twice in a row while the `coverage/` directory still exists, eslint will attempt to lint all of the `*.js` files in the `coverage/` directory and gets very red very quickly. I'm guessing this isn't desired behavior!
I'm not convinced my solution here is the best one, but it does seem to do what I'd expect it to.

Coverage directory shouldn't be linted

---

lib/client.js
test/raven.client.js

In order to support https://blog.getsentry.com/2016/07/22/environment-details.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/raven-node/179)

add in environment option

---

lib/parsers.js
test/raven.parsers.js

This mimics the behavior from raven-python and other clients.
cc @macqueen @mattrobenolt @psergus
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/raven-node/181)

Drop process.env, pass IP as User interface (refs #58, #169, #170)

---

lib/client.js
lib/parsers.js
package.json
test/raven.client.js

We're using this in raven-js, might as well use here too.
cc @macqueen @mattrobenolt 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/raven-node/182)

Use json-stringify-safe to prevent circular references (refs #102)

---

lib/client.js
lib/utils.js

Removing unnecessary single quotes in keys for objects. It's unnecessary because the keys don't have any special characters, so we can use JSON notation for them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/raven-node/164)

Removes unnecesary single quotes in keys

---

.eslintrc
index.js
lib/client.js
lib/middleware/connect.js
lib/parsers.js
lib/transports.js
lib/utils.js
package.json
test/raven.client.js
test/raven.parsers.js
test/raven.utils.js

I made the eslintrc more strict and cleaned up a few minor things that that caught; it wasn't much so these code changes are pretty minor, but the PR is mostly to make sure the ESLint version situation makes sense:
We're using 2.13.1 here instead of latest 3.5.0 because ESLint 3.x dropped support for node < 4. With 3.5.0 travis would fail on 0.8-0.12, but we don't have a strong reason to need ESLint 3.x, so staying on 2.x was the easiest fix for now.
Unfortunately the Travis docs didn't have anything helpful to let us run a different test command for different node versions, so if we want to upgrade to ESLint 3.x, I think the best we could do is make the lint step figure out if it's on node < 4 and if so skip linting.
/cc @benvinegar
---
This change is [<img …

Update eslint to 2.13.1, make eslintrc more strict

---

package.json

Good news: I audited each of our dependencies and they all
1) have no further dependencies
2) are pretty stable
3) are by developers I recognize
so I'm not going to worry about shrinkwrapping or anything like that as long as we have the versions pinned.
The version updates reflected here are all pretty minor and should be fully BC.
/cc @benvinegar
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/raven-node/206)

Update and lock down dependency versions

---

lib/client.js
lib/middleware/connect.js
lib/utils.js
test/raven.client.js

- Adds client.runWithContext
- Makes express middleware use runWithContext
- Makes client.setUserContext, client.setExtraContext, and client.setTagsContext play with the nicely with the domain context from runWithContext
Tests are currently broken, working on fixing existing tests and adding tests for runWithContext.
To discuss:
- Naming, API, etc
- `onErr` param in runWithContext vs duplicating domain stuff in express middleware
Example use:
```javascript
var ctx = {
user: {
username: 'lewis'
},
tags: {...}
};
client.runWithContext(ctx, function () {
throw new Error(...); // will be caught and reported with user and tags from ctx
});
```
or:
```javascript
// omit ctx object
client.runWithContext(function () {
client.setUserContext({ username: 'lewis' });
// async stuff happens in between …
```

runWithContext and friends

---

.travis.yml
lib/client.js
lib/transports.js
lib/utils.js
test/raven.client.js
test/raven.parsers.js

Short version: addresses #213, moves the API to follow raven-js almost exactly, still maintains BC in almost all ways with old API
Details:
- captureException etc now fire their callbacks after sending to the server, as in #213 
- Moved everything to a Raven class instead of Client, following raven-js pattern/API
- We now export a default Raven instance, leading to almost-identical usage to raven-js
- Still have a Client wrapper for bc/multi-instance capabilities
- Does some other polishing/cleanups on the API changes
- Adds glue to maintain backwards compat with old API as much as possible
- None of the changes to tests actually affect any existing public API usage patterns at all
The only public API usage affected by this should be the one described by @mattrobenolt in #213, and the …

Make capture* callbacks fire after sending, more API cleanup/singletonization

---

lib/client.js
lib/middleware/connect.js

Adds new Raven-instance-oriented middleware-returning-methods:
```javascript
var Raven = require('raven');
Raven.config(dsn).install();
...
app.use(Raven.requestHandler());
...
app.use(Raven.errorHandler());
```
Also BC-ifies old raven.middleware.express.* interface to delegate to these after ensuring existence of client instance.

Middleware fixes

---

lib/client.js
test/raven.client.js

This is a little WIPpy, need to test more, but I realized 1) usefulness of an intercept function and 2) some simplifications to wrap.

Cleaning up wrap, adding intercept

---

lib/client.js
test/raven.client.js

Still todo on this PR: make sure captureException etc, we have the correct context-state-merging-hierarchy going on; stuff passed to capture method > stuff in domain context > stuff in instance-global context.

Simplify context methods to fall back on instance-global context

---

lib/client.js

Quick change, moved stuff and made `captureError` return the eventId like `captureException`.

Move set*Context to deprecations, fix captureError return value

---

package.json
test/raven.client.js

Based on reading https://www.npmjs.com/package/npm-bump and https://docs.npmjs.com/getting-started/using-tags, the plan is to set the version to this and then do:
```
npm publish --tag beta
```
which will result in installation instructions being:
```
npm install raven@beta
```
or specifically *this first* beta:
```
npm install raven@1.0.0-beta.0
```
and will avoid installing the beta when someone just does `npm install raven`.
/cc @benvinegar

Version 1.0.0-beta.0

---

lib/client.js

Deprecate/remove captureQuery

---

.eslintignore
.travis.yml
package.json
test/instrumentation/README.md
test/instrumentation/node-http.test.js
test/instrumentation/run-node-http-test.js
test/instrumentation/run.sh

/cc @benvinegar @maxbittker
This is a sort of one-off harness to run node's core http module's tests against our instrumented version of it. This gives me a good amount of confidence that our instrumentation doesn't blow anything up, but I'm still working on some raven-level "did we catch the breadcrumb off the instrumentation" type tests in addition to these.
Can you go through this readme to make sure you can run them on your system? It'll take a few minutes to clone node, but running the tests only takes ~40 seconds.

Add instrumentation tests for node-http against its own tests

---

lib/breadcrumbs.js
lib/client.js
test/raven.client.js

There's a bit of general test suite refactoring that could be done here, and I need to refactor our `uncaughtexception`/`unhandledrejection` handler stuff a bit to make `.uninstall` remove only our handlers instead of all of them, but this at least exercises our breadcrumb instrumentation and capturing. I'll worry about that stuff after the breadcrumbs PR lands.

Breadcrumb tests

---

lib/middleware/connect.js
test/raven.client.js

- Changed to use `instanceof Raven.constructor` instead of `instanceof Raven.client`
- Added deprecation warnings; these toplevel functions are the old way to do it and people should have their own instances and use the instance methods instead, rather than having to pass in an instance or let one be created for them.
Based on #245 from @dhritzkiv. Will merge into master and also cherry pick into a `releases/1.0.x` branch, then publish 1.0.1 and 1.1.1.
/cc @benvinegar

Fix middleware backwards compatibility

---

lib/client.js

In the `shouldSendCallback` function, we need the args in order to determine whether we want to send to sentry based on the current data. This is exactly how things work for the JavaScript client version of raven.

Pass kwargs into shouldSendCallback() as param

---

lib/utils.js
test/raven.utils.js

I tested this on windows and osx and everything seems to be working correctly! thank you @stambata and @seanbriceland  original PR: https://github.com/getsentry/raven-node/pull/118

Pr/118 parseStack respects windows paths 

---

lib/client.js
test/raven.client.js

Managed to repro/test that this fixes issue in #266. The test case is a little tricky but hopefully makes sense.
/cc @benvinegar @MaxBittker @rwky

Explicitly bind req/res to context domain in express requestHandler

---

docs/config.rst
lib/client.js
lib/parsers.js
test/raven.parsers.js

Should address #231. Will also add some flexibility for both #82 and another slight improvement that we can make in the requestHandler middleware for automatically-grabbing-request.
/cc @benvinegar @MaxBittker and somewhat refactors request parsing so /cc @mattrobenolt.

Adds parseUser option to control user parsing behavior

---

lib/client.js

As per comment [here](https://github.com/getsentry/raven-node/issues/254#issuecomment-281555668). I do this check in `config` so that a user can do `Raven.disableConsoleAlerts()` before `Raven.config` to avoid seeing this alert.
/cc @benvinegar - does this seem like a reasonable message and condition for "seems like a browser?"

Add alert about node vs raven-js when it seems like a browser env

---

docs/config.rst
lib/client.js
test/raven.client.js

Basically the same thing as getsentry/raven-js#885
/cc @benvinegar @dcramer

Add sampleRate config option

---

lib/breadcrumbs.js

PR #276/version 1.1.3 introduced a memory leak in our http instrumentation as reported in #295. The core issue was that we were monkeypatching `http.ClientRequest.prototype.emit` during every `ClientRequest` instantiation, instead of just during initial instrumentation, which meant that for each outbound http request made, we kept a bunch of stuff around in a closure.
Users on raven-node 1.1.3 or 1.1.4 with long-running processes that made outbound http requests found their memory usage growing steadily over time.
This PR refactors the `ClientRequest` instrumentation to only monkeypatch `http.ClientRequest.prototype.emit` once during initial Raven setup when we also monkeypatch the constructor. The monkeypatched `emit` method previously found the request url by closure reference, but now …

Fix autoBreadcrumb http instrumentation memory leak

---

CONTRIBUTING.md
lib/client.js
lib/middleware/connect.js
lib/utils.js
package.json
test/manual/README.md
test/manual/express-patient.js
test/manual/manager.js
test/manual/poke-patient.sh

Had to abuse express a bit to get this whittled down to working nicely like I wanted it to, but now it's set up to be node-clusterized so we can have a fresh process for each endpoint test so that running it all can be easy. Will finish tomorrow.
If you want to play with this for now, start up `node express-patient.js` and then either `./poke-patient.sh` or just run some of the ab commands in it.
Refs #296

Memory leak express patient app WIP

---

docs/config.rst
docs/usage.rst
lib/client.js
lib/transports.js
lib/utils.js
package.json
test/exit/capture.js
test/exit/capture_callback.js
test/exit/capture_with_second_domain_error.js
test/exit/capture_with_second_error.js
test/exit/domain_capture.js
test/exit/domain_capture_callback.js
test/exit/domain_capture_with_second_error.js
test/exit/domain_throw_on_send.js
test/exit/throw_on_fatal.js
test/exit/throw_on_send.js
test/raven.client.js
test/raven.utils.js

Two parts to this - the timing stuff, and the onFatalError stuff. Still working on the global uncaughtException part of the onFatalError stuff to make sure we capture as much as possible while avoiding recursive cases, but I tried to fill in some comments where the code is still in flux. Then I'm going to finish refactoring a bunch of tests from `patchGlobal` to `install`.
We introduce a dep on [timed-out](https://github.com/floatdrop/timed-out) which I've audited and is basically the "turn connect-timeouts and activity-timeouts into errors" logic ripped out of [request](https://github.com/request/request). This was a necessary prerequisite for us to ensure the onFatalError callback gets called no matter what happens. The timing config part might be redone to use config fields instead of …

Properly surfacing errors to preserve process exit conditions

---

lib/parsers.js

An error caught by a domain handler (from `context()` or `requestHandler`) will have a `domain` property. Domains can have references to all kinds of stuff - Express layers, server sockets, who knows what, just depends on what functions ran in the domain - and we don't really get any value from including it as an extra property on error objects like we currently do.
It's potentially confusing, could include random (maybe-sensitive) server state, and is a bunch (sometimes a *whole* bunch) of data for little value.
Previously:
After:

Don't include domain prop as extra property on Error objects

---

lib/client.js
test/raven.client.js

This basically implements a slightly more thorough version of what I described in [this comment](https://github.com/getsentry/raven-node/issues/82#issuecomment-281935866) in #82, and should also address what #92 and #93 were trying to solve.
Basically you can now do:
```javascript
Raven.setContext({ req: req });
```
and then we'll parse `req` as a node/express/koa request object the same way the `errorHandler` middleware does. We'll do the same for a req passed via kwargs to a captureException call:
```javascript
Raven.captureException(myError, { req: req });
```
and the `requestHandler` middleware now automatically adds `req` to the context (i.e. does this for you).

Parse req from context, and requestHandler sets req on context

---

docs/config.rst
lib/breadcrumbs.js
lib/client.js

Since we're publishing 2.0.0 we can do this for temporary relief for #254, as discussed privately.

Remove pg instrumentation

---

History.md
package.json

Accepting feedback on the release notes. Will publish first thing tomorrow.

Version 2.0.0

---

lib/utils.js
package.json

`cache` not used in `parseStack`
-  use cache in parseStack, prevent unnecessary reading of files

use cache in parseStack, prevent unnecessary reading of files

---

.eslintignore
.travis.yml
lib/utils.js
package.json
test/manual/express-patient.js
test/manual/poke-patient.sh
test/raven.utils.js

Fixes #319, based on the insight in #318; thanks to @asuka999 for the original insight + PR and @cveilleux for the memory leak report.
- refactors `parseStack`into a more serial-procedural style with a `readSourceFiles` helper
- adds a unit test to check that readFile is only called once per file
- adds a manual memory test for capturing an error thrown from 1000-deep callstack in a 5MB file 
- without this fix, parsing that stack and reading it multiple times concurrently would run the node process out of memory
The parseStack code in general needed some overhauling, so I went ahead and did that in addition to just fixing the concurrency control flow. It should hopefully be more robust and easier to follow now.

Parsestack refactor + tests to fix memory leak

---

.travis.yml
test/raven.parsers.js

Gonna go ahead and make sure this passes CI...

Adds Node 8 to CI

---

.eslintignore
lib/utils.js
test/fixtures/long-line.js
test/raven.utils.js

This should address most of the cases causing #153.
/cc @mattrobenolt @MaxBittker

Truncate long source context lines

---

test/instrumentation/http.test.js
test/instrumentation/run.sh

Added `--expose-internals` flag to all tests and `--expose-http2` for Node >= 8 only, as it's not supported in previous versions.
Included one edge case, where we have to remove http2 flag, as the test itself is asserting it's absence.

Update Node flags for v8.X instrumentation tests

---

.travis.yml
README.md
package.json
test/instrumentation/http.test.js

Initial PR for dropping support of Node pre v4.
- wrote message about supported LTS versions
- removed `<v4` guard from instrumentation tests
- removed v0.10 and v0.12 from TravisCI config
Related issue: https://github.com/getsentry/raven-node/issues/365

Pre Node v4 deprecation

---

lib/parsers.js
test/raven.parsers.js

Fixes: https://github.com/getsentry/raven-node/issues/350

fix: Pull Error's name from constructor, not Error itself

---

lib/client.js
lib/parsers.js
package.json
test/run.coffee
test/vendor/json-stringify-safe.js
vendor/json-stringify-safe.js

Fixes https://github.com/getsentry/raven-node/issues/171
Real changes are done in 2nd commit. 1st one is only moving to local copy of `json-stringify-safe`

Serialize Errors properties before sending to Sentry

---

lib/client.js
lib/utils.js
test/raven.client.js

This fixes correct code behavior when bundled using webpack. Otherwise, our bundled SDK will always yield `undefined` for anything we want to read from `process` variable.
And we do need to access it to gather environment information like `node` version.
Related: https://github.com/getsentry/sentry/pull/6626

fix: access 'process' through global variable

---

docs/index.rst
docs/sourcemaps.rst
docs/usage.rst

This should be enough to get this thing going.
Ref: https://github.com/getsentry/raven-node/issues/198
Related: https://github.com/getsentry/sentry/pull/6626

docs: Include Source Maps docs

---

lib/client.js

I have an application in production I noticed was crashing, but never saw any fatal errors sitting in sentry. After digging deeper I found the `uncaughtException` handler doesn't pass a level, so it defaults to `Error`. This PR fixes that.
```javascript
const raven = require('raven');
const sentry_dsn = 'INSERT DSN HERE';
const client = raven.Client(sentry_dsn);
client.install();
client.captureException(new Error('This is a regular error'));
throw new Error('This is a fatal error');
console.log('Done'); // Never reached.
```
__Before Fix:__
__After Fix:__

Fix reporting fatal errors

---

lib/client.js
test/raven.client.js

currently, context is lost in case of an unhandled promise rejection. This fix keeps track of the context by looking into the rejected promise domain. This fix has been tested in my production environment and seems to do the trick there.

fix: preserve context in for rejected promises

---

package.json
test/fixtures/file with spaces in path.js
test/raven.utils.js

This just required a bump in the version of `stack-trace`.

Handle spaces in paths

---

docs/coffeescript.rst
docs/index.rst
docs/integrations/connect.rst
docs/integrations/koa.rst
docs/usage.rst

Tested by symlinking into `sentry-docs`.

docs: Remove private DSNs from the docs

---

lib/client.js

`new Error(message)` creates a stack trace. There's no need to throw and catch it.

fix: Remove a redundant try-catch block

---

bin/raven
lib/parsers.js
lib/utils.js
test/raven.parsers.js
test/raven.utils.js

By default, we emit a `transaction` now instead of the culprit.

ref: Emit transaction instead of culprit
