getsentry/raven-node

README.md, lib/middleware/connect.js
See: http://stackoverflow.com/questions/10390658/how-to-handle-code-exceptions-in-node-js
=> Handle asyncrhonous errors

test/raven.client.js
Basically used events API instead of messing around w/ internals ... seemed to solve it.
https://nodejs.org/api/events.html
Tested with Node 0.10.x, 0.12.x, 4.0.x.
=> Fix tests for node 4.0

lib/parsers.js, test/raven.parsers.js
cc @macqueen @mattrobenolt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/raven-node/177)
=> Copy `req.user` to user interface if present (fixes #160)

docs/config.rst
Most of the language was taken from raven-js, where the options are identical.
cc @macqueen @mattrobenolt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/raven-node/183)
=> Update sorely out-of-date docs

docs/config.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/raven-node/184)
=> Fix formatting issues in docs

lib/client.js, test/raven.client.js
cc @macqueen @fboutin-pmc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/raven-node/185)
=> Fix environment not attached from opts/kwargs

docs/integrations/express.rst
@getsentry/javascript
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/raven-node/191)
=> Fix DSN template placeholder in express integration docs

lib/transports.js, package.json, test/raven.client.js, test/raven.utils.js
This has been gone for years
:skull::skull::skull::skull::skull::skull::skull::skull::skull::skull:
@LewisJEllis @benvinegar
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/getsentry/raven-node/197)
=> rm -rf udp

.travis.yml
=> Add Node v7 to travis

History.md
=> History - fix issue number for process.env

lib/client.js
=> Make sure cb exists before calling it in should-not-send case

docs/integrations/koa.rst
=> Fix koa doc variable name mixup, fixes #260

docs/config.rst, lib/breadcrumbs.js, test/raven.client.js
Fixes #263 
/cc @gbartlett9089 @MaxBittker @benvinegar
=> Fix postgres/pg name mismatch

lib/utils.js, test/raven.utils.js
=> Add test for node core library frames being marked as not in_app

lib/client.js, package.json, test/raven.client.js
Took #252 and added a test.
/cc @benvinegar @vineethawal
=> Capture breadcrumbs from global context

History.md, package.json
=> Version 1.1.3

lib/breadcrumbs.js, test/raven.client.js
Fixes #285 
/cc @benvinegar @MaxBittker
=> Use util.format to get message string in console instrumentation

docs/usage.rst, lib/client.js
=> Add req kwarg parsing docs, simplify req parsing in errorHandler

lib/client.js, test/raven.client.js
=> Don't parse empty `req` properties

History.md, package.json
@benvinegar thoughts on the patch notes?  existing memory leak tests seemed to pass 👍
=> Version 2.1.0

lib/client.js, test/raven.client.js
=> delete kwargs.req after parsing

README.md
Per https://github.com/getsentry/raven-js/pull/1022 change
=> Add logo to readme to streamline SDK readme

docs/integrations/index.rst, docs/integrations/loopback.rst
via https://github.com/getsentry/raven-node/issues/162#issuecomment-321205014
=> docs: Add Loopback integration docs

docs/config.rst
Fixes https://github.com/getsentry/raven-node/issues/150
=> docs: Mention git-rev usage in release config attribute

docs/integrations/index.rst, docs/integrations/sails.rst
Refs https://github.com/getsentry/raven-node/issues/128 https://github.com/getsentry/raven-node/pull/381
=> docs: Add Sails.js integration docs

docs/config.rst
Closes https://github.com/getsentry/raven-node/issues/373
=> docs: Add name config description and optional ENV vars

lib/client.js
It's making the investigation of performance issues easier.
**New Relic**
**Chrome Dev Tool**
Related to:
- https://github.com/i18next/i18next-express-middleware/pull/144
- https://github.com/helmetjs/helmet/pull/165
=> Use a named function for the middleware over an anonymous

docs/integrations/loopback.rst
See my issue comment here for more information: https://github.com/getsentry/raven-node/issues/162#issuecomment-362711803
=> Update loopback docs
